const SUPABASE_URL = 'https://yaridrmtmfxkfcdvnqnl.supabase.co';
const SUPABASE_KEY = 'sb_publishable_-wgggIdtKIqPvDN4WY0EfA_48__9QvJ';
const ALLOWED_EMAILS = new Set(['tyler109j@gmail.com', 'kaylajilljoyce@gmail.com']);
const plannerDb = window.supabase.createClient(SUPABASE_URL, SUPABASE_KEY, { auth: { autoRefreshToken: true, detectSessionInUrl: true, flowType: 'pkce', persistSession: true } });
const authPanel=document.querySelector('#authPanel'), boardPanel=document.querySelector('#boardPanel'), signInButton=document.querySelector('#signInButton'), authMessage=document.querySelector('#authMessage'), boardMessage=document.querySelector('#boardMessage'), refreshButton=document.querySelector('#refreshButton'), choreList=document.querySelector('#choreList'), dateLabel=document.querySelector('#dateLabel'), progressLabel=document.querySelector('#progressLabel'), progressCount=document.querySelector('#progressCount'), progressBar=document.querySelector('#progressBar');
let currentUser=null, chores=[];
const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,character=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[character]));
function localDateKey(value=new Date()){const date=value instanceof Date?value:new Date(value);return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;}
function routineSteps(item){return Array.isArray(item.details?.steps)?item.details.steps:[];}
function routineComplete(item,dateKey){const steps=routineSteps(item),completed=new Set(item.details?.step_completions?.[dateKey]||[]);return Boolean(item.details?.completed_dates?.includes(dateKey)||(steps.length&&completed.size>=steps.length));}
function occursToday(item,dateKey){if(item.status==='cancelled'||item.details?.paused)return false;const base=item.planned_for||item.starts_at?.slice(0,10)||item.due_at?.slice(0,10)||dateKey;if(dateKey<base||(item.details?.end_date&&dateKey>item.details.end_date))return false;const recurrence=item.details?.recurrence||'';if(item.item_type==='routine'&&recurrence==='weekdays'){const day=new Date(`${dateKey}T12:00:00`).getDay();return day>=1&&day<=5;}return !recurrence||dateKey===base;}
function render(){const dateKey=localDateKey(),doneCount=chores.filter(item=>item.done).length,total=chores.length;dateLabel.textContent=new Intl.DateTimeFormat('en-US',{weekday:'long',month:'long',day:'numeric'}).format(new Date());progressCount.textContent=total?`${doneCount} of ${total}`:'';progressBar.style.width=total?`${Math.round(doneCount/total*100)}%`:'0%';progressLabel.textContent=total&&doneCount===total?'Amazing work, team!':doneCount?'Youâ€™re doing great!':'Letâ€™s get started!';if(!total){choreList.innerHTML='<div class="empty-board"><strong>All clear!</strong><span>There are no chores for today.</span></div>';return;}choreList.innerHTML=chores.map(item=>`<article class="chore-card ${item.item_type} ${item.done?'complete':''}"><div class="chore-icon" aria-hidden="true">${item.item_type==='routine'?'â­':'ðŸ§¹'}</div><div><p class="chore-kind">${item.item_type==='routine'?'Routine':'Chore'}</p><h2 class="chore-name">${escapeHtml(item.title)}</h2>${item.item_type==='routine'&&routineSteps(item).length?`<p class="chore-detail">${routineSteps(item).length} step${routineSteps(item).length===1?'':'s'}</p>`:''}</div><button class="done-button" type="button" data-chore-id="${item.id}" aria-pressed="${item.done}">${item.done?'âœ“ Done':'Mark done'}</button></article>`).join('');}
async function loadChores(){if(!currentUser)return;boardMessage.textContent='Loading todayâ€™s choresâ€¦';const {data,error}=await plannerDb.from('planner_items').select('*').in('item_type',['task','routine']).neq('status','cancelled').order('updated_at',{ascending:false});if(error){boardMessage.textContent='The chore board could not load. Please try again.';boardMessage.classList.add('error');return;}const dateKey=localDateKey();chores=(data||[]).filter(item=>occursToday(item,dateKey)).map(item=>({...item,done:item.item_type==='routine'?routineComplete(item,dateKey):item.status==='completed'}));boardMessage.textContent='';boardMessage.classList.remove('error');render();}
async function markDone(id){const item=chores.find(candidate=>candidate.id===id);if(!item||!currentUser)return;const dateKey=localDateKey(),button=document.querySelector(`[data-chore-id="${CSS.escape(id)}"]`);if(button)button.disabled=true;let mutation;if(item.item_type==='routine'){const details={...(item.details||{})},dates=new Set(details.completed_dates||[]);if(item.done)dates.delete(dateKey);else dates.add(dateKey);mutation={details:{...details,completed_dates:[...dates]},updated_via:'website'};}else mutation={status:item.done?'active':'completed',updated_via:'website'};const {data,error}=await plannerDb.from('planner_items').update(mutation).eq('id',id).select('id').maybeSingle();if(error||!data){boardMessage.textContent='That change could not be saved. Please try again.';boardMessage.classList.add('error');if(button)button.disabled=false;return;}await loadChores();}
async function signIn(){authMessage.textContent='Opening Google sign-inâ€¦';const {error}=await plannerDb.auth.signInWithOAuth({provider:'google',options:{redirectTo:`${location.origin}${location.pathname}`}});if(error)authMessage.textContent=error.message;}
async function updateUser(user){currentUser=user&&ALLOWED_EMAILS.has(String(user.email||'').toLowerCase())?user:null;if(!currentUser){authPanel.hidden=false;boardPanel.hidden=true;if(user)authMessage.textContent='This board is limited to the Tyler and Kayla family accounts.';return;}authPanel.hidden=true;boardPanel.hidden=false;await loadChores();}
signInButton.addEventListener('click',signIn);refreshButton.addEventListener('click',loadChores);choreList.addEventListener('click',event=>{const button=event.target.closest('[data-chore-id]');if(button)markDone(button.dataset.choreId);});plannerDb.auth.onAuthStateChange((_event,session)=>{updateUser(session?.user||null);});plannerDb.auth.getSession().then(({data})=>updateUser(data.session?.user||null));
